### ISSUE TITLE
ADO Repositories doesn't end with .git

### ISSUE THREAD

**Issue by gkarthiks** [Humbedooh/clc#2]
Hi, Thank you for this amazing tool. I love it. I just want to bring up one thing to your knowledge. 

I think you are force validating the repo URL to have `.git`. But the ADO repositories don't have that suffix even in htps scheme. 

So I commented on the following locally in clc.js file [here](https://github.com/Humbedooh/clc/blob/main/server/webui/js/clc.js#L70-L74) and works just fine.

```diff
-     // if (!repo_url.endsWith('.git')) {
-    //     alert("Repository URL must end with .git!");
-    //     return
-    // }
-    // if (repo_url.length > 10 && repo_url.endsWith('.git')) {
+    if (repo_url.length > 10 ) {
```

Let me know if you want it as a pull request. I can do that.

**Comment by Humbedooh** [comment]
I realize it's a simple (and right now, binary) check that could be improved upon.
What if we had a warning instead of a hard break?
Something like "You are trying to check out a repository URL that does not end in .git. Are you sure this is what you intended?" [yes/no]

**Comment by gkarthiks** [comment]
Yeah, I like that. Thanks for the fix. I will close this issue.
