### ISSUE TITLE
Crash when out of space

### ISSUE THREAD

**Issue by mscherer** [Humbedooh/clc#4]
We deployed CLC on our openshift instance, and today, the server crashed due to being out of space, with this traceback:
```
==== Serving up CLC good vibes at http://0.0.0.0:8080 ====
Starting scheduled scan of /srv/scratch/git/freeipa.git...
Traceback (most recent call last):
  File "/srv/server/main.py", line 196, in <module>
    pubsub_server.run()
  File "/srv/server/main.py", line 180, in run
    loop.run_until_complete(self.server_loop(loop))
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/srv/server/main.py", line 175, in server_loop
    await plugins.background.run_tasks(self)
  File "/srv/server/plugins/background.py", line 433, in run_tasks
    await scan_project(server, server.data.projects[repo], path)
  File "/srv/server/plugins/background.py", line 144, in scan_project
    assert proc.returncode == 0, "Git fetch returned non-null: " + str(stderr)
AssertionError: Git fetch returned non-null: b'error: unable to create temporary file: No space left on device\nfatal: failed to write object\nfatal: unpack-objects failed\n'
```

Of course, openshift restarted, but then it crashed again. And again, and again, until Openshift stopped restarting.

I increased the disk space, but I think assert is a rather big hammer for this error, and i also think lack of space shouldn't block the rest of the software.

**Comment by Humbedooh** [comment]
Yeah that should probably just leave a warning somewhere.
Perhaps a warning log that'll show up somewhere in the UI so you have an idea what's going on.

**Comment by Humbedooh** [comment]
I believe it should be addressed now, and when a scan fails, it'll log a warning and display on the project analysis page instead. The warning will disappear when the underlying issue has been fixed.
