### ISSUE TITLE
Allow to remove a project from the UI

### ISSUE THREAD

**Issue by mscherer** [Humbedooh/clc#5]
There is no way to remove a project from the UI, so users can only add things and not cleanup. This inconvenient in the case of a hosted service, as ssh + shell access is more complex than the UI.

**Comment by Humbedooh** [comment]
Done in 1119082a76ca59bf609e0683d70fa3921b461791 and e5834fac836a017a9e9cf0fe32467af5c15b7182, apologies for not referencing the ticket in it.
